### ISSUE TITLE
psid 0x204097

### ISSUE THREAD

**Issue by KenWhitesell** [nprobert/Wireshark-DSRC#4]
First and most importantly, **thank you** for releasing this!

We're getting map messages from some RSUs being broadcast with PSID 0x204097, which is identified as CV Pilot MAP distribution per https://standards.ieee.org/products-services/regauth/psid/public.html. Are you interested in a pull request with the changes? (Note, it also involves changes to packet-ieee1609dot2.h and packet-wsmp.c)

Also, as an FYI, this continues to work great with the current Wireshark 3.5 rc.

**Comment by nprobert** [comment]
Yes, please.  And thanks!

I've seen that PSID before.  Sadly, not everybody keeps their RSUs updated and configured correctly.  Some are still running pre-2016 stuff.

**Comment by nprobert** [comment]
I've noticed that CV Pilot MAP message have this weird extra byte just before the start of the J2735 data in the 1609.2 unsecured layer.

**Comment by nprobert** [comment]
No, the files to be changed are in epan/dissectors/asn1/ieee1609dot2/

**Comment by nprobert** [comment]
Ok, it works.
